# Generated by Django 2.0.3 on 2018-03-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('student_name', models.CharField(max_length=50)),
                ('student_age', models.IntegerField()),
                ('student_rollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student_app.School')),
            ],
        ),
    ]
